// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Nl-_N5K_2xa4qjCqfV0YugWI02J-lec',
    appId: '1:121198675863:web:1d12b1ebe3f5d079f6a6d2',
    messagingSenderId: '121198675863',
    projectId: 'spudtom-ai',
    authDomain: 'spudtom-ai.firebaseapp.com',
    storageBucket: 'spudtom-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9eed5ErqcbG9tUIwxhl3S9lcmM7ee_rY',
    appId: '1:121198675863:android:5c96edf8e5d09b07f6a6d2',
    messagingSenderId: '121198675863',
    projectId: 'spudtom-ai',
    storageBucket: 'spudtom-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9jr8q9uibiQSIObSiUc0Q8FpF1NV-Ar0',
    appId: '1:121198675863:ios:00772d46a0ef37b9f6a6d2',
    messagingSenderId: '121198675863',
    projectId: 'spudtom-ai',
    storageBucket: 'spudtom-ai.firebasestorage.app',
    iosBundleId: 'com.example.spudtom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9jr8q9uibiQSIObSiUc0Q8FpF1NV-Ar0',
    appId: '1:121198675863:ios:00772d46a0ef37b9f6a6d2',
    messagingSenderId: '121198675863',
    projectId: 'spudtom-ai',
    storageBucket: 'spudtom-ai.firebasestorage.app',
    iosBundleId: 'com.example.spudtom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Nl-_N5K_2xa4qjCqfV0YugWI02J-lec',
    appId: '1:121198675863:web:0f2979b2386a11f0f6a6d2',
    messagingSenderId: '121198675863',
    projectId: 'spudtom-ai',
    authDomain: 'spudtom-ai.firebaseapp.com',
    storageBucket: 'spudtom-ai.firebasestorage.app',
  );
}
